### ISSUE TITLE
AttributeError: 'Context' object has no attribute 'temp_override'

### ISSUE THREAD

**Issue by Vap0r1ze** [TobyLobster/ImportLDraw#84]
Coming from #73

I get an error when I try to import an LDraw file ([canetest.zip](https://github.com/TobyLobster/ImportLDraw/files/12038584/canetest.zip)):
<pre>
07:09:08.98 [importldraw] The LDraw Parts Library path to be used is: C:\Program Files\Studio 2.0\ldraw
07:09:08.98 [importldraw] Use LSynth Parts requested
07:09:08.98 [importldraw] Standard-res primitives selected
07:09:08.98 [importldraw] Loading files
07:09:09.64 [importldraw] Creating NodeGroups
07:09:09.64 [importldraw] createBlenderDistanceToCenterNodeGroup #create
07:09:09.65 [importldraw] createBlenderVectorElementPowerNodeGroup #create
07:09:09.65 [importldraw] createBlenderConvertToNormalsNodeGroup #create
07:09:09.65 [importldraw] createBlenderConcaveWallsNodeGroup #create
07:09:09.65 [importldraw] createBlenderSlopeTextureNodeGroup #create
07:09:09.65 [importldraw] createBlenderFresnelNodeGroup #create
07:09:09.65 [importldraw] createBlenderReflectionNodeGroup #create
07:09:09.65 [importldraw] createBlenderDielectricNodeGroup #create
07:09:09.65 [importldraw] createBlenderLegoStandardNodeGroup #create
07:09:09.65 [importldraw] createBlenderLegoTransparentNodeGroup #create
07:09:09.65 [importldraw] createBlenderLegoTransparentFluorescentNodeGroup #create
07:09:09.65 [importldraw] createBlenderLegoRubberNodeGroup #create
07:09:09.65 [importldraw] createBlenderLegoRubberTranslucentNodeGroup #create
07:09:09.65 [importldraw] createBlenderLegoEmissionNodeGroup #create
07:09:09.66 [importldraw] createBlenderLegoChromeNodeGroup #create
07:09:09.66 [importldraw] createBlenderLegoPearlescentNodeGroup #create
07:09:09.66 [importldraw] createBlenderLegoMetalNodeGroup #create
07:09:09.66 [importldraw] createBlenderLegoGlitterNodeGroup #create
07:09:09.66 [importldraw] createBlenderLegoSpeckleNodeGroup #create
07:09:09.66 [importldraw] createBlenderLegoMilkyWhiteNodeGroup #create
07:09:09.66 [importldraw] Creating Blender objects
07:09:11.43 [importldraw] Number of vertices: 210830
07:09:11.71 [importldraw] Number of convex hull vertices: 120
07:09:11.71 [importldraw] Centre object
07:09:11.71 [importldraw] Positioning Camera
Python: Traceback (most recent call last):
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_importldraw\importldraw.py", line 399, in execute
    loadldraw.loadFromFile(self, self.filepath)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 4520, in loadFromFile
    with bpy.context.temp_override(area=area):
AttributeError: 'Context' object has no attribute 'temp_override'

location: <unknown location>:-1
</pre>

**Comment by Vap0r1ze** [comment]
It seems that the `bpy.context.temp_override` was [added in 3.2](https://wiki.blender.org/wiki/Reference/Release_Notes/3.2/Python_API#Additions), so that version might be a requirement for the current state of this add-on. I'll test and see if that fixes it

**Comment by Vap0r1ze** [comment]
This issue _does_ go away for me in blender 3.6 :tada:

![image](https://github.com/TobyLobster/ImportLDraw/assets/20448879/ca502a36-6489-456e-a1dd-920041ea2570)

**Comment by ReeceTaylor512** [comment]
Did you do anything to get it to work in 3.6? Re-Exploring this issue and I can't seem to get it to work

**Comment by Vap0r1ze** [comment]
@ReeceTaylor512 I didn't do anything to resolve the `'Context' object has no attribute 'temp_override'` error other than updated to 3.6

However, before this I was having the same issue as people in #73, and I found the solution and posted it in that thread

**Comment by TobyLobster** [comment]
I have just released a new version for Blender 4 that should fix this issue.
